### ISSUE TITLE
Getting error while running examples

### ISSUE THREAD

**Issue by it-nerdy** [axt/angr-utils#17]
Hi,

I cloned the repository and try to run the examples. But I am getting this error while runnning.

Traceback (most recent call last):
  File "/home/sankara/PycharmProjects/angr-utils/examples/plot_cfg/plot_cfg_example.py", line 21, in <module>
    analyze(proj, main.addr, "ais3")
  File "/home/sankara/PycharmProjects/angr-utils/examples/plot_cfg/plot_cfg_example.py", line 13, in analyze
    plot_cfg(cfg, "%s_%s_cfg" % (name, func.name), asminst=True, vexinst=False, func_addr={addr:True}, debug_info=False, remove_imports=True, remove_path_terminator=True)
  File "/home/sankara/PycharmProjects/angr-utils/angrutils/visualize.py", line 31, in plot_cfg
    vis.process(cfg.graph) 
  File "/home/sankara/.local/lib/python2.7/site-packages/bingraphvis/base.py", line 310, in process
    return self.output.generate(graph)
  File "/home/sankara/.local/lib/python2.7/site-packages/bingraphvis/output.py", line 214, in generate
    dotfile.write("{}.{}".format(self.fname, self.format), format=self.format)
  File "/home/sankara/.local/lib/python2.7/site-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/sankara/.local/lib/python2.7/site-packages/pydot.py", line 1867, in create
    raise OSError(*args)
OSError: [Errno 2] "dot" not found in path.

I tried to debug but would could not able to fix. 

on pydot.py line number 1855 

        try:
            p = subprocess.Popen(
                cmdline,
                env=env,
                cwd=tmp_dir,
                shell=False,
                stderr=subprocess.PIPE, stdout=subprocess.PIPE)
        except OSError as e:
            if e.errno == os.errno.ENOENT:
                args = list(e.args)
                args[1] = '"{prog}" not found in path.'.format(
                    prog=prog)
                raise OSError(*args)
            else:
                raise

This particular part is throwing, "No such file" error. Could you please guide me?

**Comment by axt** [comment]
Hi! 

The `dot` utility is needed to convert the graphs from the _raw dot_ format, to anything else, like  _pdf_, _svg_, _png_, etc. The format can be specified as a parameter to `plot_cfg`, the default setting is _png_.

You can do two things:
 - The `dot`utility is provided by `graphviz`, if you install graphviz the problem should disappear.
 - Specify a `format="raw"`parameter to `plot_cfg`: in this case the output will be the graph in the _raw dot_ format. Still if you want to view that, you will need `graphviz` to render it, so I recommend to install `graphviz`.

**Comment by it-nerdy** [comment]
format="raw" parameter works fine. I am able to see raw files. I installed `graphviz` but still error persists, in case of format="png". May be i will use other ways to convert raw file to visible image file.

**Comment by axt** [comment]
With the `dot` utility you can use the following command, to convert the raw files into a `png`:
```
dot -Tpng -o out.png in.raw
```
you should check, if this is working for you. If it does, then the error lays somewhere in the `pydot` package, I use that to interact with `dot`. My guess is that somehow the dot utility is not found by the package, or it is not executable, or something like that.

I usually generate raw files (because its much faster), and view them with `xdot`, which also uses the `dot` command for rendering. (https://github.com/jrfonseca/xdot.py)

Environment issues are hard to debug, I would do an 
```
strace -f python script_to_generate_the_graph.py |& grep 'dot' 
```
to see what happens under the hood.

**Comment by it-nerdy** [comment]
Thanks for you quick responses, it helped me in resolving the issue. I got the point, actually `pydot` is invoking a command that uses dot utility (it is running internally `dot -Tpng -o out.png in.raw` ) . Since I don't have xdot installed in my system it is was throwing error. Now, I installed xdot tool in my linux system, issue is resolved. I can generate png files directly. May be, you can document it some where, in requirements to install xdot. Thanks again.

**Comment by axt** [comment]
I think I figured out what happened. 

The `xdot` package is not needed for the library to function correctly, but the xdot package has 
graphviz as a dependency, so when you installed xdot you also installed graphviz.

My guess is, that when you tried to install graphviz before, instead of the system package `graphviz` which is the graph rendering tool, you installed the python package called `graphviz`, which is just a python wrapper around the utility. 

```
$ apt-file find -F '/usr/bin/dot'
graphviz: /usr/bin/dot
```

```
$ apt-file show xdot
xdot: /usr/bin/xdot
xdot: /usr/lib/python3/dist-packages/xdot-0.7.egg-info/PKG-INFO
xdot: /usr/lib/python3/dist-packages/xdot-0.7.egg-info/dependency_links.txt
xdot: /usr/lib/python3/dist-packages/xdot-0.7.egg-info/entry_points.txt
xdot: /usr/lib/python3/dist-packages/xdot-0.7.egg-info/top_level.txt
xdot: /usr/lib/python3/dist-packages/xdot.py
xdot: /usr/share/applications/xdot.desktop
xdot: /usr/share/doc/xdot/changelog.Debian.gz
xdot: /usr/share/doc/xdot/copyright
xdot: /usr/share/man/man1/xdot.1.gz

```
