### ISSUE TITLE
WARNING | 2018-07-16 17:19:33,677 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.

### ISSUE THREAD

**Issue by xjtuncy** [axt/angr-utils#18]
When I run the example plot_cdg_example.py, it warning :angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups. And the node  in simple1_cdg.png doesn't contains the MIPS instruction.
![simple1_cdg](https://user-images.githubusercontent.com/22024804/42764044-2f7a39ee-8947-11e8-8a96-0fc1c1f39b4d.png)

**Comment by axt** [comment]
Hi! Sorry, somehow I missed the email notification about this issue, just stumbled upon it now. 
If the problem still exists, and you can send me the binary that produces this problem, I can have a look at it.

**Comment by Ch111p** [comment]
Hi. It Seems like I met the same problem like this.
I tried the example binary ais3-crackme, and the same code in README, But the output just like
![ais3_cfg.png](https://i.loli.net/2020/06/10/VXW38rdNPT5ghHD.png)
I was thought it's might be caused by the different version of capstone, at first the version is 4.0.2, so i tried to switched to capstone 3.0.5, but in that version it can't even run. Said "module 'arm' has no attribute 'ARM_GRP_CALL'", So I changed to capstone 4.0.1 But it still can't works. The output is just like the pitcure. I'm sure asminst is True while running.
The OS is Ubuntu18, WSL1.
