### ISSUE TITLE
Exporting to GraphML?

### ISSUE THREAD

**Issue by Manouchehri** [axt/angr-utils#2]
Should work since NetworkX has GraphML support I believe.

**Comment by axt** [comment]
Sorry for my late answer. The code in its current form is a bit 'proof-of-concept'-like. I'm planning a major refactor of it, which will make it easier to add these kind of features to it.

Since I don't know GraphML, and my focus is on other ideas/features, I can't promise I will add GraphML support by myself, but I will make it easy to be added, and I'm happy to take pull-requests, if you would like to make it. The only thing I ask for is just to wait till the refactor (hopefully in 2-3 weeks).

May I ask in which application you use GraphML?

**Comment by axt** [comment]
Networkx also supports Graphviz (.dot) export, but the graph misses all the "fancy" features/metadata. 
You can try it like this:

```
import networkx as nx
nx.write_dot(cfg.graph, 'output.dot')
```

To illustrate it, here is the networkx graph visualized:

![cica](https://cloud.githubusercontent.com/assets/759365/16068105/56cd6746-32c3-11e6-9f1e-7a55339a5e02.png)

But the idea is great, to actually create the graph with all the metadata appended to the nodes and edges in networkx (don't know it too much) or some other graphing library, before visualization. I will consider it when doing the refactor.

**Comment by Manouchehri** [comment]
I was looking into trying Gephi; I managed to get it working by using GEXF instead (which NetworkX supports).

https://networkx.github.io/documentation/networkx-1.10/reference/readwrite.gexf.html
