### ISSUE TITLE
RuntimeError when running angrutils.plot_ddg_data(ddg.simplified_data_graph, xxx)

### ISSUE THREAD

**Issue by penhoi** [axt/angr-utils#22]
Hi,
There is a runtime error, could you fix it?
Thanks!

------------------code-------------------
angrutils.plot_ddg_data(ddg.simplified_data_graph, "xxx", project=proj)

---------------Error message-----------
RuntimeError: dictionary changed size during iteration

**Comment by axt** [comment]
Sorry, I will not have time for this probably until the end of May. 
Also,  please note that DDG is broken in angr, so even after someone fixes it, it will not work as expected.

**Comment by axt** [comment]
It works for me, but the graph is completely useless. I don't follow `angr` since 1.5 years, but I think DDG is deprecated, and buggy, and instead there are other solutions provided (VariableRecovery + ReachingDefinitions + LightEngine) to do this kind of analysis.  

If it is still an issue, and you can give me a PoC (a binary + a few lines of code what generates the error), I can have a look, otherwise I will close this.
