### ISSUE TITLE
Save CFG to a file instead of rendering in new window

### ISSUE THREAD

**Issue by H0r53** [axt/angr-utils#24]
I'm using angr strictly in a shell environment. I would like to use the **plot_cfg** function, or something similar, to generate an image (perhaps in a PNG format) on my local file system, instead of rendering the image in a new window (which clearly won't work in a shell environment). Looking through the available arguments I don't see any options for saving the rendered CFG to a file instead of displaying it. Is such a feature available or something that could be incorporated in a future release?

**Comment by axt** [comment]
Hi. It's saved to a file by default :-). 

If you specify 'png' for the format parameter, then it will render it into an image, if you specify 'raw' then it will be saved in graphviz dot format, which could be rendered later, for example with the 'xdot' utility. I would propose the later option, because layouting and rendering the graph to an image can take a lot of time, especially if the graph is large, what you don't necessary need to do during analysis time.

**Comment by H0r53** [comment]
That is perfect! What a great utility. Sorry for opening a non-issue. I knew it had to be something simple. Thank you!
