### ISSUE TITLE
plot_cfg(): Plotted CFG is not readable

### ISSUE THREAD

**Issue by ghost** [axt/angr-utils#25]
Using plot_cfg(), generated PNG for CFG which is not readable at all when call depth is 5 or more.
Code snippet below:
```
            main = proj.loader.main_object.get_symbol(FUNC_NAME)
            start_state = proj.factory.blank_state(addr=main.rebased_addr)
            if CFG_TYPE == "emulated":
                cfg = proj.analyses.CFGEmulated(fail_fast=True, starts=[main.rebased_addr], initial_state=start_state, resolve_indirect_jumps=False, call_depth=CALL_DEPTH)
```

Basically when call depth was kept to 5, then it was blurred upon zooming, however, with depth 1 or 3, the plotted graphs were readable.
<img width="774" alt="Screenshot 2020-01-14 at 11 19 10" src="https://user-images.githubusercontent.com/40387738/72902801-01690c00-3d24-11ea-9ebb-9f476185223d.png">

**Comment by axt** [comment]
I think it's a problem of the `dot` command, when saving large graphs into png.

I would propose, that instead of using the `png` format as output, add `format='raw'` parameter to `plot_cfg`, to save the graph in raw format. (Or you can try `format='dot'`, which is similar to raw, but calculates the graph layout before dumping the data, slower at creation, easier when using the graph).

You can view this raw graph for example with the `xdot` command in linux (I prefer this way over png), but I guess there are other tools to view `dot` files on any OS.

The framework uses the `dot` command from the `graphviz`, to turn a raw graph into png:
```
dot -Tpng graph.raw > graph.png
```
If you figure out what command options, or graph attributes need to be added, to make the render not blurry, i can add support for it in the framework.

**Comment by ghost** [comment]
Many thanks for the input @axt 
It is working fine using format as ```SVG```. So basically no changes were done with respect to ```dot``` command, just added ```format='svg'``` within ```plot_cfg()```.
