### ISSUE TITLE
Are there limitations to plot_cfg()?

### ISSUE THREAD

**Issue by allen-sparks** [axt/angr-utils#27]
I am trying to plot the cfg of notepad.exe as an exercise.
I am using CFGFast and CFGEmulated.

CFGFast()
>>>proj = angr.Project('notepad.exe', load_options={'auto_load_libs': False})
>>>#main = proj.loader.main_object.get_symbol("main")    #cant find main, no symbols
>>>cfg = proj.analyses.CFGFast(show_progressbar=True)
>>>len(cfg.functions)
415
>>>len(cfg.graph.nodes())
8086
>>>plot_cfg(cfg, 'test', asminst=True, remove_imports=True, remove_path_terminator=True)
#ends up just hanging here

CFGEmulated()
>>>proj = angr.Project('notepad.exe', load_options={'auto_load_libs': False})
>>>#main = proj.loader.main_object.get_symbol("main")    #cant find main, no symbols
>>>cfg = proj.analyses.CFGEmulated(show_progressbar=True)
>>>len(cfg.functions)
365
>>>len(cfg.graph.nodes)
12501
>>>plot_cfg(cfg, 'test', asminst=True, remove_imports=True, remove_path_terminator=True)
#hangs here as well

1) I could see how producing a PNG of 8k+ nodes would take a long time. I was just wondering if there was anything I was missing or if there is a limit to the size of the binary.

2) For me, the cfgs are nice to haves, but I'm just trying to get a list of all the possible addresses the program could jump to. With that goal in mind, which analyses would be better suited for finding all the addresses?

**Comment by axt** [comment]
1) Yes, there are limitations. 
- Graphviz layouting of the graph doesn't scale well, probably O(n^2) or above, so for 8k+ nodes, it  will never finish.
- The size of the png is also limited, so if you have a lot of nodes, they will be unreadable.

I would propose you to create a different plot for every function, you can specify a `func_addr` to `plot_cfg` which contains the function addresses you want to include in the plot, like in the example here:
https://github.com/axt/angr-utils/blob/master/examples/plot_cfg/plot_cfg_example.py#L13-L15

That is also not the optimal solution, because it will transform the whole graph from angr representation to [bingraphvis](github.com/axt/bingraphvis/) representation every time you are plotting a function, which will fit your usecase, but if you wanna optimize on that, or on project with lot more symbols, you will need to go a level deeper, and use bingraphvis directly:

Extracted this code from here: 
https://github.com/axt/angr-utils/blob/master/angrutils/visualize.py#L17
```
    vis = AngrVisFactory().default_cfg_pipeline(cfg, asminst=True, vexinst=False, comments=True)
    vis.add_transformer(AngrRemoveImports(cfg.project))
    vis.add_transformer(AngrRemoveSimProcedures())

    // you can add your own graph preprocessing building blocks here, for example color some interesting nodes, etc
    vis.add_node_annotator(ColorNodes(filter=lambda node: node.obj.addr in interesting_nodes, fillcolor='lightgreen'))

    // when the whole graph is built, we save save all the functions it has, by specifying the `filter` parameter of `vis.process`
    // this will not rebuild the whole graph, just select the interesting parts
    for addr,func in proj.kb.functions.items():
        vis.set_output(DotOutput("%s_%s_cfg" % (name, func.name), format='raw'))    
        vis.process(cfg.graph, lambda node: node.obj.function_address == addr ) 
```
Its not documented, but here you can find some info about that: https://github.com/axt/bingraphvis/issues/4

Also I would recommend to use `format='raw'`, which will only produce the `dot` files as the output, without any layouting (so its pretty fast), or you can use format `format='dot'`, which also produce the `dot` files but this time layout info is also added, which needs to be computed. 

I personally prefer to use the `raw` format and layout it "on-demand", when I view the `raw` files with the `xdot` utility. You can even search for node addresses in the graph when you are using `xdot` instead of plain images. Later you can later convert the `dot` files to images if you want, for example using the `dot` command of graphviz:
```
dot -Tpng  -ooutput.png input.dot
```

Just a note, if you are using CFGEmulated, with context sensitivity greater than 1, that can raise interesting issues from the point of rendering, see this ticket here: https://github.com/axt/angr-utils/issues/21

2) I can't answer you that question, better if you ask that on the `angr` slack channel or mailing list.

**Comment by allen-sparks** [comment]
Thank you so much for your prompt and detailed answer. I really appreciate you taking the time to answer my question. Hope you have a good one!
