### ISSUE TITLE
Interactive Web View? (d3.js)

### ISSUE THREAD

**Issue by Manouchehri** [axt/angr-utils#3]
Was wondering if it might be possible to export a graph to D3.js.

**Comment by axt** [comment]
The same goes here as in issue #2, the code needs to be refactored first.

Since `d3.js` is a drawing library, i'm not sure it can be called export.

But I like the idea. One could create an interactive CFG visualizer / explorer application in d3.js using angr-utils as a backend.

I would like to have something like this (currently i'm trying to patch `xdot` with some features like this), but its a big work, and my frontend skills are mediocre, and there is a big todo-list with the visualizer, so I don't think I will create it by myself.

**Comment by Manouchehri** [comment]
I found out that there's some existing projects that should already work with NetworkX.

https://github.com/fkling/JSNetworkX (example: http://jsnetworkx.org/examples.html#example1)

https://github.com/Jverma/NetworkxD3

**Comment by axt** [comment]
Thanks for the links. 

I definiately would like to have something like this. 

Lets get back to this topic, after I'm done with the refactor of the code.

**Comment by SOSCapture** [comment]
Could you please give me a hand about this problem?
![screenshot from 2017-04-04 19 59 07](https://cloud.githubusercontent.com/assets/26480137/24687910/52326728-1971-11e7-998f-72ecc3785dfe.png)

**Comment by axt** [comment]
The `dot` utility (from `graphviz`) is needed if you want your output be `.png` which is the default for `plot_cfg`.

Two possible solutions:
- install `graphviz` so you will have the `dot` utility
- add a format='raw' parameter to `plot_cfg`, in this case your graphs will be in raw `.dot` format, and you need to use `xdot` or some other tool to view them.

**Comment by axt** [comment]
Since I don't see that I will have time for this in the future and angr-management now supports interactive graphs, I'm closing this issue.
