### ISSUE TITLE
 No module named 'angrutils'

### ISSUE THREAD

**Issue by wangzhankun** [axt/angr-utils#31]
Hi, guys, your  `setup.py` of `angrutils ` is wrong. The name should be `angrutils` but you set it to `angr-utils` which leads to the error `ModuleNotFoundError: No module named 'angrutils'`.

**Comment by axt** [comment]
Hey! I'm not an expert in python, but I think there is nothing wrong with `setup.py`. The name of the module is 'angr-utils', and it provides the package 'angrutils'. I've seen various projects using this kind of layout. 

Did two quick tests:
1) install from pypi:
```
mkvirtualenv test1
pip install angr-utils
python -c 'import angrutils'; echo $?
0
```
2) editable install from git:
```
mkvirtualenv test2
pip install -e ./angr-utils
python -c 'import angrutils'; echo $?
0
```
My guess is that the problems you experienced are caused by something else in your setup.
