### ISSUE TITLE
I got an error when I was import angr

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [axt/angr-utils#34]
It gives me this:

Traceback (most recent call last):
  File "E:\Document\porgram\科研项目\src\angr_other_learn\angr-utils\examples\myExample\test.py", line 1, in <module>
    import angr
  File "D:\Program Files\Anaconda3\lib\site-packages\angr\__init__.py", line 22, in <module>
    from .utils.formatting import setup_terminal
  File "D:\Program Files\Anaconda3\lib\site-packages\angr\utils\__init__.py", line 5, in <module>
    from . import enums_conv
  File "D:\Program Files\Anaconda3\lib\site-packages\angr\utils\enums_conv.py", line 6, in <module>
    from ..protos.primitives_pb2 import Edge
  File "D:\Program Files\Anaconda3\lib\site-packages\angr\protos\__init__.py", line 10, in <module>
    from . import primitives_pb2
  File "D:\Program Files\Anaconda3\lib\site-packages\angr\protos\primitives_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor' from 'google.protobuf' (unknown location)

here is the sourse code

import angr

it gives me the error in the first line of the code.
I don't know what is going on, and I coudn't find effective solutions on Google. please help me

**Comment by axt** [comment]
Hey. Sorry for my late response, I hope you could solve it in the meantime.

This repository is just a CFG visualization utility for 'angr', but except for the name, it has no relation to the 'angr' project at all. 

You should try to ask for help on the official angr slack channel: https://angr.io/invite/

**Comment by Lost-little-dinosaur** [comment]
ok, thank you, but now I get another question:Does the tool support parsing binaries encoded in multiple languages and operating systems? So far, I have tried Python, C, Go and other languages coded in Windows and Linux respectively, and the result is that only the files compiled in C in Linux can be analyzed normally. I don't know whether my operation is wrong or the tool does not support those files
![image](https://user-images.githubusercontent.com/82520400/193755124-3b65dae3-e2b6-45bd-8701-b15d56af919b.png)

**Comment by axt** [comment]
The only purpose of this utility is to visualize the control flow graphs, created by the 'angr' CFG analysis. If you see that the displayed CFG-s are not correct or complete, it has a high chance that the problem is with the CFG-s created by angr, and not with the visualization.

The error displayed above indicates that angr failed to resolve the jumptable correctly, because it doesn't know how to interpret the Iop_CasCmpNE64 VEX instruction. This will lead to inaccurate or partial CFGs, because it will not know on which addresses to continue the CFG recovery, so even a large portion of your control flow graph could be missing. To solve the error above, you would need to add handling of that instruction to angr or create a custom jump table resolver for your binary. Also, you can try to submit an issue to the angr project, and wait till someone picks it up, or ask for help about it on the slack channel, maybe someone already has a solution or help you where to start with it. They really have a supportive community.

I don't use angr since like 5-6 years, so I have no idea, what is the current status of the project in supporting various binaries.
