### ISSUE TITLE
Obtain the graph create by process

### ISSUE THREAD

**Issue by frapik99** [axt/angr-utils#8]
Hi,
first of all thanks for the project. I would suggest to make possible for a user to have the ```graph``` back. For example, once you call ```set_output``` and subsequently ```process``` you can store the png generated by the libraries. I would like to not be forces to set the output and maybe just call ```get_graph``` and obtain the graph returned by the ```process``` function. Is it already possible?

Thanks

**Comment by axt** [comment]
Hi! Wasn't sure which is your problem, so I have multiple answers:

1) If your problem is that the output of the `plot_xxx` functions in `visualize.py` are `png` files:
 - you can change that by specifying a format='dot', or format='raw' parameter, to produces layouted or raw dot files.

2) If you want to have access to the internal graph used by `bingraphvis` without plotting to a file: 

You can access it multiple ways, the heart of the `Vis` object is the `VisPipeLine` which handles all the components of the library (source, annotators, content, transformers), except the `Output`. 

So you can access the graph like this:
```
vis = AngrVisFactory().default_cfg_pipeline(cfg)
vis.add_transformer([...])
graph = vis.pipeline.process()
```
or you can setup the pipeline in a standalone way:
```
vp = VisPipeLine()
vp.set_source(AngrCFGSource())
vp.add_content(AngrCFGHead())
graph = vp.process()
```

**Can you share me your usecase, why you need the internal graph?** 

I'm asking this, because I have plans to change this part of the code in the future, so if you base anything on the internal graph representation, probably you will need to refactor your code later. But if I know how you use it, I can take care when doing the changes, that I don't remove support for your usecase.

**Comment by frapik99** [comment]
thanks @axt , very nice answer. I think I would go for the latter solution... In my case I need it because I would like to have an "interactive" graph maybe using ```d3.js``` or in general it would be useful to anyone that wants to store/use the graph in another way and not just "see" it.

UPDATE:

```
In [105]: vis = AngrVisFactory().default_cfg_pipeline(cfg)
In [106]: graph = vis.pipeline.process()
In [107]: graph.nodes
Out[107]: set()
```

So I must specific at least one transformer?

Finally I used the following code:

```
In [141]: vis = AngrVisFactory().default_cfg_pipeline(cfg)
In [142]: vis.preprocess(cfg.graph)
In [143]: g = vis.pipeline.process()
In [144]: g.nodes
```

Is it ok?

Thanks again

**Comment by axt** [comment]
Originally I planned the  `Output` component for this. It gets called with the result of the processing pipeline, and handles it any way it wants. So for example, one could create an `InteractiveOutput` class, what could be used instead of `DotOutput`, and would open a graphical display and render the graph into it. (I admit, that this desing has limitations, and for exampe its especially bad for interacting with 'd3.js')

Creating an interactive display is a challenging task. Most of the `bingraphvis` structure/API is created for the basic usecase of creating non-interactive graphs. If you manage to build something usable on top of `bingraphvis` I can adapt the API of it to support your needs.

I also advise you to check https://github.com/angr/angr-management, before writing you own interactive display, @ltfish added a lot of nice features to it (check this screenshot):

![screenshot from 2017-05-10 17 14 39](https://cloud.githubusercontent.com/assets/759365/25906269/6e26a97c-35a4-11e7-87c4-5fef50ab2892.png)

**Comment by frapik99** [comment]
Thanks @axt , I'll have a look on the project you suggested.

Anyway, would not be better to have a different class for each output type you want to create? So a user would just need to call ```set_output(DisideredFormat())``` and it would be done... Isn't possible?

Thanks

**Comment by axt** [comment]
Just saw that you updated the previous comment. Yes its correct that way, but I would advice you to call `preprocess` on `vis.pipeline` instead of on `vis`. At the moment they do the same, but it can happen that the `vis` objects functionality changes in the future and that can introduce some incoherence if you call the prepocess of the outer object, and then the process of the inner. 

```python
vis = AngrVisFactory().default_cfg_pipeline(cfg)
vis.pipeline.preprocess(cfg.graph)
g = vis.pipeline.process()
g.nodes
```

Not sure I understand the question about the output. It works that way you described, you can create your own class, and then use `set_output(YourOutput())`.

**Comment by frapik99** [comment]
All solved for now.

Thanks
